spring:
  application:
    name: depth-chart-manager

server:
  port: 8080
  servlet:
    contextPath: /depth-chart-manager-api/v1

  datasource:
    url: jdbc:postgresql://localhost:5432/playbook_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect